
services:
  user-service:
    build:
      context: ./services/user-service
    container_name: user-service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql+asyncpg://user:password@postgres:5432/user_db"

  order-service:
    build:
      context: ./services/order-service
    container_name: order-service
    ports:
      - "8001:8001"

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
