version: "3.8"

services:
  # 👉 User Service
  user-service:
    build:
      context: ./services/user-service
    container_name: user-service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@postgres:5432/devops_db
    command: ["./wait-for-it.sh", "postgres:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  # 👉 Order Service
  order-service:
    build:
      context: ./services/order-service
    container_name: order-service
    ports:
      - "8001:8001"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]

  # 👉 PostgreSQL
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devops_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
