name: CI for Microservices

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: >-
          --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: List running containers
        run: docker ps
